### ISSUE TITLE
It is not working 

### ISSUE THREAD

**Issue by Luismm2311** [nwilging/hass-discord-bot#2]
I configured everything as you explained but when I start the service I don't get de message that I'm supposed, I get this:
`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
ifelse: fatal: unable to exec /start.sh: Exec format error
[cmd] /start.sh exited 126
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.`

My system info (I'm running hassio on as Raspberry Pi 3B+):
## System Health

version | core-2021.4.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.4.83-v7
arch | armv7l
timezone | America/Mexico_City

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4947
Installed Version | 1.12.1
Stage | running
Available Repositories | 776
Installed Repositories | 7

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 10 de mayo de 2021 19:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 5.13
-- | --
update_channel | stable
supervisor_version | supervisor-2021.04.0
docker_version | 19.03.15
disk_total | 56.4 GB
disk_used | 6.7 GB
healthy | true
supported | true
board | rpi3
supervisor_api | ok
version_api | ok
installed_addons | ESPHome (1.16.2), Node-RED (9.0.1), Check Home Assistant configuration (3.7.0), File editor (5.3.0), Home Assistant Google Drive Backup (0.104.3), Samba share (9.3.1), SSH & Web Terminal (8.2.0), HassIO Discord Bot (0.3.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 0
views | 4
mode | storage

</details>

**Comment by nwilging** [comment]
I know this issue is very old, but here I am :)

`start.sh` isn't actually needed, and the app can be started via an `entrypoint` in the dockerfile. I will get this fixed.

**Comment by nwilging** [comment]
confirmed working on v0.4.0 on my HA machine:

`core-2022.2.0`
`supervisor-2022.03.1`
`Home Assistant OS 7.4`
